### ISSUE TITLE
Not working on version 1.2.1

### ISSUE THREAD

**Issue by erpnedir** [enricofrigo/kanboard#1]
Hi, I installed this plugin at latest version but it is not working.
Any ideas or help?

Application version: 1.2.1
PHP version: 5.6.34
PHP SAPI: litespeed
OS version: Linux 3.10.0-427.36.1.lve1.4.47.el7.x86_64
Database driver: mysql
Database version: 5.6.38
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by enricofrigo** [comment]
Hi,
I use this plugin on 1.2.1 and it works on 
PHP version: 5.6.19
PHP SAPI: apache2handler
OS version: Linux 2.6.18-423.el5
Database driver: sqlite
Browser: Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
I installed the kanboard on Apache, maybe it's the PHP SAPI?
Could you try with a different server?

Regards

**Comment by enricofrigo** [comment]
Hi,
could you retry now?

Let me know if it works now.

Regards

**Comment by erpnedir** [comment]
hi,
I copied the new version of the plugin directory, no change. It still shows "1 comment" on tooltip.
I think the plugin do not override KB default behaviour. 
How to proceed?

By the way: Thank you very much for this plugins. It was one of the missing thins in KB as stated here: [https://github.com/kanboard/kanboard/issues/3171](url)

**Comment by enricofrigo** [comment]
Hi,
can you see the icons on the right side of the task?

![kb-comment](https://user-images.githubusercontent.com/11732741/38799607-6a8b3eb0-4154-11e8-840d-6debf88b9d79.jpg)

Regards

**Comment by erpnedir** [comment]
No, just the original icon!
![enrico-comment](https://user-images.githubusercontent.com/16351692/38799768-119c528e-416e-11e8-8d29-4e1eb0e454e2.png)

**Comment by enricofrigo** [comment]
Hi,
in the Settings->Integrations menu the enable comments tooltip is selected?

Regards

**Comment by erpnedir** [comment]
Hi Enrico,
That was missing. I am very sorry for missing this. 
Now your plugin is working.
Thanks a lot!

**Comment by enricofrigo** [comment]
Hi,
don't worry, you're welcome.
I add th check to  Settings->Integrations menu into Installation instructions

Regards

**Comment by rtfmpliz** [comment]
Hi Enrico

I've got the comment tooltip at the end of every task board,
but in the tooltip, onlys shows blanks

I'm using version 1.2.0

![screenshot 58](https://user-images.githubusercontent.com/9409853/39127735-14b2f3ac-4730-11e8-93b4-8718a4acb439.png)

**Comment by enricofrigo** [comment]
Hi,
I try with a fresh new 1.2.0 installation and it works on
PHP version: 5.6.19
PHP SAPI: apache2handler
OS version: Linux 2.6.18-423.el5
Database driver: sqlite
Browser: Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

could you send other information in setting configuration, and which other plugins you already installed?

Regards

**Comment by rtfmpliz** [comment]
maybe because I'm using custom stylesheet,

I'll try with normal style sheet

>  I already tried normal style sheet, problem still persist

Application version: 1.2.0
PHP version: 5.6.0
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: mysql
Database version: 5.7.14
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**tomorrow** I'll try install with default setting


here my installed plugin

Broadcast|Frédéric Guillot|1.0.0
:-----:|:-----:|:-----:
Broadcast messages to users via the application or by email.| | 
Calendar|Frédéric Guillot|1.1.0
Calendar view for Kanboard| | 
Chat|Frédéric Guillot|1.0.1
Minimalist Chat for Kanboard.| | 
Comment Only Resctrictions for Project Viewers|Craig Crosby|0.0.1
Add Commenting abilities for Project Viewers| | 
Comment Tooltip|Enrico Frigo|0.0.1
Show all comments as tooltip| | 
Coverimage|BlueTeck|1.0.38.0
Coverimage Function| | 
Css|Author|0.0.1
This plugin add a new stylesheet and override default styles.| | 
DueDate|David Morlitz|1.0.2
Force columns to be sorted by due date| | 
Gantt|Frédéric Guillot|1.0.2
Gantt charts for Kanboard| | 
Instantactions|"Mehari| Reith"
This plugin adds instant actions to tasks in the board view.| | 
Metadata|BlueTeck + Daniele Lenares|1.0.33.2
Manage Metadata| | 
Milestone|Olivier Maridat|1.1.1
The Milestone Plugin for Kanboard adds a section for milestones to show their related tasks.| | 
Self-Registration|Frédéric Guillot|1.0.7
Allow people to sign up themselves on Kanboard| | 
Relationgraph|Xavier Vidal <xavividal@gmail.com>|0.1.3
Show relations between tasks using a graph| | 
Auto Email Action Extender|Craig Crosby|0.0.2
"Add the automatic actions to Send a task by email to the creator or assignee of the task. Also| included is an action to send a notification via email to user| creator
Subtaskdate|Manuel Raposo|1.0.1
Add a new due date field to subtasks| | 
TaskBoardDate|Frédéric Guillot|1.0.2
Add a new date field for tasks to define the visibility on the board and dashboard| | 
TaskMoveOnDueDate|David Morlitz|0.0.1
Automatically move a task to a specific column on the date| | 
Telegram|Manu Varkey|1.2.0
Receive notifications on Telegram| |

**Comment by enricofrigo** [comment]
Hi,
try with the last version, you can dowload it from here; 
https://github.com/enricofrigo/kanboard/raw/master/plugin-comment-tooltip/releases/download/v1.0.0/CommentTooltip.zip

Regards

**Comment by rtfmpliz** [comment]
Hi Enrico,
now my problem is solved, I'm using your last version
Thank you

![screenshot 141](https://user-images.githubusercontent.com/9409853/40399515-f7980470-5e67-11e8-8c45-d710e9a5a442.png)

الله يهدك 
Allahu yahdik_
